version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'fit2023'
      MYSQL_ROOT_PASSWORD: 'fit2023'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db-data:/var/lib/mysql